### PR TITLE
Added Commands.

### PR DESCRIPTION
**Pull request by applqpak**

### CODE REVIEW

**Comment by TheDragonRing** [comment]
Thx for the command! I'm just having problems with line 46 in the Main.php (the @mkdir bit)

**Comment by applqpak** [comment]
Ah ok.

**Comment by applqpak** [comment]
What's the issue on L46?

**Comment by TheDragonRing** [comment]
When I try compiling it with pmt.mcpe.me it comes up with an error saying:
PHP Parse error: syntax error, unexpected '@' in /var/www/tmp/5/QuickJoinMsg/src/TheDragonRing/QuickJoinMsg/Main.php on line 46
Errors parsing /var/www/tmp/5/QuickJoinMsg/src/TheDragonRing/QuickJoinMsg/Main.php

Sorry for the slow reply

**Comment by applqpak** [comment]
Ok, I'll take a look.

**Pull request merged**
